/**
 * Generates `supabase/seed.sql` from the same canonical TypeScript fixtures
 * (`src/data/organizations.ts`, `src/data/jobs.ts`, `src/data/candidates.ts`)
 * used by local demo mode, so Supabase mode and guest mode always describe
 * the exact same fictional catalog with matching ids.
 *
 * Run with: `npm run db:generate-seed`
 * (invokes `node --experimental-strip-types --import ./scripts/register-ts-resolver.mjs scripts/generate-seed.ts`)
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { organizations } from "../src/data/organizations";
import { jobs } from "../src/data/jobs";
import { candidates } from "../src/data/candidates";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function sqlString(value: string | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNumber(value: number | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return String(value);
}

function sqlBool(value: boolean): string {
  return value ? "true" : "false";
}

function sqlTextArray(values: string[] | null | undefined): string {
  if (!values || values.length === 0) return "'{}'::text[]";
  const escaped = values
    .map((v) => `"${v.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`)
    .join(",");
  return `'{${escaped.replace(/'/g, "''")}}'::text[]`;
}

function sqlJsonb(value: unknown): string {
  if (value === null || value === undefined) return "null";
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

const lines: string[] = [];

lines.push("-- OfferLoop — generated seed data");
lines.push("-- DO NOT EDIT BY HAND. Generated by `npm run db:generate-seed` from");
lines.push("-- src/data/organizations.ts, src/data/jobs.ts, and src/data/candidates.ts.");
lines.push("-- Every row below is entirely fictional (see PRODUCT_SPEC.md).");
lines.push("");
lines.push("begin;");
lines.push("");

lines.push(
  "-- organizations ------------------------------------------------------------",
);
for (const org of organizations) {
  lines.push(
    `insert into public.organizations (id, name, slug, initials, industry, short_description, logo_style, is_fictional, is_active) values (` +
      [
        sqlString(org.id),
        sqlString(org.name),
        sqlString(org.slug),
        sqlString(org.initials),
        sqlString(org.industry),
        sqlString(org.shortDescription),
        sqlJsonb(org.logoStyle),
        sqlBool(org.isFictional),
        sqlBool(org.isActive),
      ].join(", ") +
      `) on conflict (id) do nothing;`,
  );
}
lines.push("");

lines.push("-- jobs -----------------------------------------------------------------");
for (const job of jobs) {
  lines.push(
    `insert into public.jobs (id, organization_id, slug, title, description, responsibilities, qualifications, benefits, location, work_arrangement, employment_type, experience_level, salary_min, salary_max, signing_bonus, currency, category, skills, fictional_manager_name, simulated_posted_days_ago, is_active) values (` +
      [
        sqlString(job.id),
        sqlString(job.organizationId),
        sqlString(job.slug),
        sqlString(job.title),
        sqlString(job.description),
        sqlTextArray(job.responsibilities),
        sqlTextArray(job.qualifications),
        sqlTextArray(job.benefits),
        sqlString(job.location),
        sqlString(job.workArrangement),
        sqlString(job.employmentType),
        sqlString(job.experienceLevel),
        sqlNumber(job.salaryMin),
        sqlNumber(job.salaryMax),
        sqlNumber(job.signingBonus ?? null),
        sqlString(job.currency),
        sqlString(job.category),
        sqlTextArray(job.skills),
        sqlString(job.fictionalManagerName),
        sqlNumber(job.simulatedPostedDaysAgo),
        sqlBool(job.isActive),
      ].join(", ") +
      `) on conflict (id) do nothing;`,
  );
}
lines.push("");

lines.push("-- fictional_candidates ---------------------------------------------------");
for (const candidate of candidates) {
  lines.push(
    `insert into public.fictional_candidates (id, slug, display_name, initials, headline, summary, location, years_experience, skills, education, recent_role, work_history, projects, achievements, preferred_work_arrangement, expected_salary_min, expected_salary_max, availability, avatar_style, is_fictional, is_active) values (` +
      [
        sqlString(candidate.id),
        sqlString(candidate.slug),
        sqlString(candidate.displayName),
        sqlString(candidate.initials),
        sqlString(candidate.headline),
        sqlString(candidate.summary),
        sqlString(candidate.location),
        sqlNumber(candidate.yearsExperience),
        sqlTextArray(candidate.skills),
        sqlString(candidate.education),
        sqlString(candidate.recentRole),
        sqlJsonb(candidate.workHistory),
        sqlJsonb(candidate.projects),
        sqlTextArray(candidate.achievements),
        sqlString(candidate.preferredWorkArrangement),
        sqlNumber(candidate.expectedSalaryMin),
        sqlNumber(candidate.expectedSalaryMax),
        sqlString(candidate.availability),
        sqlJsonb(candidate.avatarStyle),
        sqlBool(candidate.isFictional),
        sqlBool(candidate.isActive),
      ].join(", ") +
      `) on conflict (id) do nothing;`,
  );
}
lines.push("");
lines.push("commit;");
lines.push("");

const outputPath = path.join(__dirname, "..", "supabase", "seed.sql");
writeFileSync(outputPath, lines.join("\n"), "utf-8");

console.log(
  `Generated ${outputPath} with ${organizations.length} organizations, ${jobs.length} jobs, and ${candidates.length} candidates.`,
);
